---
name: ga_InfluxDBv1
version: "0.0.3"
slug: ga_influxdbv1
description: Scalable datastore for metrics, events, and real-time analytics
url: https://github.com/hassio-addons/addon-influxdb
codenotary: codenotary@frenck.dev
ingress: true
ingress_port: 1337
ingress_stream: true
panel_icon: mdi:chart-areaspline
startup: services
homeassistant: 0.92.0b2
hassio_api: true
arch:
  - aarch64
  - amd64
  - armv7
init: false
map:
  - share:rw
  - ssl
ports:
  80/tcp: null
  8086/tcp: 8086
  8088/tcp: 8088
ports_description:
  80/tcp: Web interface (Not required for Ingress)
  8086/tcp: InfluxDB server
  8088/tcp: RPC service for backup and restore
auth_api: true
options:
  auth: true
  reporting: true
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  envvars: ## optimized for ressource constrained devices 
    - name: INFLUXDB_REPORTING_DISABLED
      value: "true"
    - name: INFLUXDB_DATA_CACHE_MAX_MEMORY_SIZE
      value: "64m"
    - name: INFLUXDB_DATA_MAX_WAL_SIZE
      value: "16m"
    - name: INFLUXDB_DATA_WAL_FSYNC_DELAY
      value: "100ms"
    - name: INFLUXDB_DATA_TSM_USE_MADV_WILLNEED
      value: "false"
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  auth: bool
  reporting: bool
  ssl: bool
  certfile: str
  keyfile: str
  envvars:
    - name: match(^INFLUXDB_([A-Z0-9_])+$)
      value: str
  leave_front_door_open: bool?
image: ghcr.io/greenautarky/ga_influxdbv1-{arch}
